export const assetPlaceholder = [
  {
    id: "1",
    assetNo: "L9",
    mfgYr: "2009",
    make: "Jungheinrich",
    model: "EKX515K",
    sn: "FN392249",
    description: "Combi 1 B.O.P.",
    location: "PM1",
    inspectionFreq: "24",
    serviceProvider: "Jungheinrich",
    nextService: 2024-11-18,
    status: "GREEN"
  },
]

export const assetData = [
  {
    id: "1",
    assetNo: "L9",
    mfgYr: "2009",
    make: "Jungheinrich",
    model: "EKX515K",
    sn: "FN392249",
    description: "Combi 1 B.O.P.",
    location: "PM1",
    inspectionFreq: "24",
    serviceProvider: "Jungheinrich",
  },
  {
    id: "2",
    assetNo: "L22",
    mfgYr: "2004",
    make: "Jungheinrich",
    model: "EKX515K",
    sn: "FN305744",
    description: "Combi 2 B.O.P.",
    location: "PM1",
    inspectionFreq: "24",
    serviceProvider: "Jungheinrich",
  },
  {
    id: "3",
    assetNo: "L50",
    mfgYr: "2012",
    make: "Skyjack",
    model: "SJ111-3226",
    sn: "27012386",
    description: "M.E.W.P.",
    location: "PM1",
    inspectionFreq: "0",
    serviceProvider: "Reddilift",
  },
  {
    id: "4",
    assetNo: "L55",
    mfgYr: "2005",
    make: "Toyota",
    model: "7FBH20",
    sn: "23957",
    description: "Battery Forklift",
    location: "PM1",
    inspectionFreq: "0",
    serviceProvider: "Reddilift",
  },
  {
    id: "5",
    assetNo: "L73",
    mfgYr: "2012",
    make: "BT",
    model: "SWE200D",
    sn: "6206894",
    description: "Battery stacker truck",
    location: "PM1",
    inspectionFreq: "0",
    serviceProvider: "Reddilift",
  },
  {
    id: "6",
    assetNo: "L69",
    mfgYr: "2012",
    make: "BT",
    model: "SWE200D",
    sn: "6120804",
    description: "Battery stacker truck",
    location: "PM1",
    inspectionFreq: "0",
    serviceProvider: "Reddilift",
  },
  {
    id: "7",
    assetNo: "Rented",
    mfgYr: "2006",
    make: "Toyota",
    model: "6FBRE16",
    sn: "E31061",
    description: "Battery reach forklift",
    location: "PM1",
    inspectionFreq: "0",
    serviceProvider: "Reddilift",
  },
  {
    id: "8",
    assetNo: "L15",
    mfgYr: "2014",
    make: "Genie",
    model: "GS2632",
    sn: "GS3214C - 11805",
    description: "M.E.W.P.",
    location: "PM3 HSE Annex",
    inspectionFreq: "0",
    serviceProvider: "Reddilift",
  },
  {
    id: "9",
    assetNo: "L81",
    mfgYr: "2008",
    make: "Mid-Western Lifts",
    model: "MRL",
    sn: "81024",
    description: "Electric Hydraulic Passenger Lift",
    location: "PM1",
    inspectionFreq: "0",
    serviceProvider: "Orona Mid Western",
  },
  {
    id: "1",
    assetNo: "L0",
    mfgYr: "0",
    make: "AMT Galway Ltd",
    model: "CWR400",
    sn: "2002",
    description: "Cardboard baler",
    location: "PM1",
    inspectionFreq: "0",
    serviceProvider: "",
  },
  {
    id: "11",
    assetNo: "L26",
    mfgYr: "2007",
    make: "",
    model: "",
    sn: "",
    description: "",
    location: "PM0",
    inspectionFreq: "0",
    serviceProvider: "",
  },
  {
    id: "12",
    assetNo: "L45",
    mfgYr: "2011",
    make: "Genie",
    model: "GS2632",
    sn: "GS3211C-849",
    description: "M.E.W.P.",
    location: "PM2 HSE",
    inspectionFreq: "0",
    serviceProvider: "Reddilift",
  },
  {
    id: "13",
    assetNo: "L85",
    mfgYr: "2005",
    make: "JLG",
    model: "JLG 2030ES",
    sn: "1200004954",
    description: "M.E.W.P.",
    location: "PM2 HSE",
    inspectionFreq: "0",
    serviceProvider: "Reddilift",
  },
  {
    id: "14",
    assetNo: "L57",
    mfgYr: "2005",
    make: "Jungheinrich",
    model: "EKX513",
    sn: "FN325485",
    description: "Combi B.O.P.",
    location: "PM3",
    inspectionFreq: "0",
    serviceProvider: "Reddilift",
  },
  {
    id: "15",
    assetNo: "L60",
    mfgYr: "2002",
    make: "Jungheinrich",
    model: "ETX-K150KSG100",
    sn: "7.4204.54.04",
    description: "Combi B.O.P.",
    location: "PM3",
    inspectionFreq: "0",
    serviceProvider: "Reddilift",
  },
  {
    id: "16",
    assetNo: "L66",
    mfgYr: "2012",
    make: "Toyota",
    model: "8FBET20",
    sn: "FSW-A450 11191",
    description: "Battery fork lift",
    location: "PM3",
    inspectionFreq: "0",
    serviceProvider: "Reddilift",
  },
  {
    id: "17",
    assetNo: "L0",
    mfgYr: "0",
    make: "Gradeall Int Ltd",
    model: "GV500",
    sn: "GV514400",
    description: "Baler",
    location: "PM3",
    inspectionFreq: "0",
    serviceProvider: "Reddilift",
  },
  {
    id: "18",
    assetNo: "L35",
    mfgYr: "2010",
    make: "BT",
    model: "SWE200D",
    sn: "6103301",
    description: "Battery stacker truck",
    location: "PM3",
    inspectionFreq: "0",
    serviceProvider: "Reddilift",
  },
  {
    id: "19",
    assetNo: "L83",
    mfgYr: "2018",
    make: "ORONA",
    model: "MRL",
    sn: "EXIE61012MW",
    description: "Electric Hydraulic Passenger Lift",
    location: "PM3",
    inspectionFreq: "0",
    serviceProvider: "Orona Mid Western",
  },
  {
    id: "20",
    assetNo: "L38",
    mfgYr: "2012",
    make: "Jungheinrich",
    model: "EKX515",
    sn: "FN376545",
    description: "Combi B.O.P.",
    location: "PM4",
    inspectionFreq: "0",
    serviceProvider: "Reddilift",
  },
  {
    id: "21",
    assetNo: "L28/L94",
    mfgYr: "0",
    make: "Toyota",
    model: "7FB25",
    sn: "12429",
    description: "Battery Forklift",
    location: "PM4",
    inspectionFreq: "0",
    serviceProvider: "Reddilift",
  },
  {
    id: "22",
    assetNo: "L82",
    mfgYr: "2018",
    make: "ORONA",
    model: "MRL",
    sn: "EXIE75512MW",
    description: "Electric Hydraulic Passenger Lift",
    location: "PM4",
    inspectionFreq: "0",
    serviceProvider: "Orona Mid Western",
  },
  {
    id: "23",
    assetNo: "L84",
    mfgYr: "2019",
    make: "HIDRAL",
    model: "EH/DC-3000",
    sn: "EH-29918 XIE02222MW",
    description: "Electric Hydraulic Goods Lift",
    location: "PM4",
    inspectionFreq: "0",
    serviceProvider: "Orona Mid Western",
  },
  {
    id: "24",
    assetNo: "L90",
    mfgYr: "2010",
    make: "Combilift",
    model: "C3000",
    sn: "C00028718",
    description: "Combi Lift",
    location: "PM1",
    inspectionFreq: "12",
    serviceProvider: "Combilift Ltd.",
  },
  {
    id: "25",
    assetNo: "L94",
    mfgYr: "2020",
    make: "Genie",
    model: "GS1932",
    sn: "GEN1932XIL1005",
    description: "M.E.W.P.",
    location: "PM1",
    inspectionFreq: "12",
    serviceProvider: "Reddilift",
  },
  {
    id: "26",
    assetNo: "L100",
    mfgYr: "2020",
    make: "Orona",
    model: "RSC51F",
    sn: "EXIE75512MW",
    description: "Electric Hydraulic Lift",
    location: "PM4",
    inspectionFreq: "12",
    serviceProvider: "Orona Mid Western",
  },
  {
    id: "27",
    assetNo: "L101",
    mfgYr: "2017",
    make: "Toyota",
    model: "8FBM20T",
    sn: "35013773",
    description: "Battery Forklift",
    location: "PM3",
    inspectionFreq: "24",
    serviceProvider: "Toyota Ireland",
  },
  {
    id: "28",
    assetNo: "L102",
    mfgYr: "2015",
    make: "Hyster",
    model: "H2.0FT",
    sn: "G15V03769Y",
    description: "LPG Forklift",
    location: "PM2",
    inspectionFreq: "24",
    serviceProvider: "Combilift Ltd.",
  },
  {
    id: "29",
    assetNo: "L103",
    mfgYr: "2021",
    make: "Combilift",
    model: "C3000",
    sn: "C00031150",
    description: "Combi Lift",
    location: "PM1",
    inspectionFreq: "12",
    serviceProvider: "Combilift Ltd.",
  },
  {
    id: "30",
    assetNo: "L104",
    mfgYr: "2018",
    make: "Genie",
    model: "GS2032",
    sn: "GEN2032TIV1836",
    description: "M.E.W.P.",
    location: "PM3",
    inspectionFreq: "12",
    serviceProvider: "Reddilift",
  },
  {
    id: "31",
    assetNo: "L105",
    mfgYr: "2022",
    make: "ORONA",
    model: "MRL",
    sn: "EXIE86002MW",
    description: "Electric Hydraulic Passenger Lift",
    location: "PM4",
    inspectionFreq: "24",
    serviceProvider: "Orona Mid Western",
  },
  {
    id: "32",
    assetNo: "L106",
    mfgYr: "2019",
    make: "Toyota",
    model: "8FBM20T",
    sn: "35015780",
    description: "Battery Forklift",
    location: "PM2",
    inspectionFreq: "12",
    serviceProvider: "Toyota Ireland",
  },
  {
    id: "33",
    assetNo: "L107",
    mfgYr: "2015",
    make: "Genie",
    model: "GS3246",
    sn: "GEN3246EIL1715",
    description: "M.E.W.P.",
    location: "PM1",
    inspectionFreq: "12",
    serviceProvider: "Reddilift",
  },
  {
    id: "34",
    assetNo: "L108",
    mfgYr: "2015",
    make: "Toyota",
    model: "8FBM20T",
    sn: "35012780",
    description: "Battery Forklift",
    location: "PM3",
    inspectionFreq: "12",
    serviceProvider: "Toyota Ireland",
  },
  {
    id: "35",
    assetNo: "L109",
    mfgYr: "2018",
    make: "Jungheinrich",
    model: "ETX-K150KSG100",
    sn: "FN434545",
    description: "Combi B.O.P.",
    location: "PM2",
    inspectionFreq: "12",
    serviceProvider: "Jungheinrich",
  },
  {
    id: "36",
    assetNo: "L110",
    mfgYr: "2021",
    make: "Toyota",
    model: "8FBM20T",
    sn: "35019780",
    description: "Battery Forklift",
    location: "PM3",
    inspectionFreq: "24",
    serviceProvider: "Toyota Ireland",
  },
  {
    id: "37",
    assetNo: "L111",
    mfgYr: "2023",
    make: "Toyota",
    model: "8FBM20T",
    sn: "35020781",
    description: "Battery Forklift",
    location: "PM4",
    inspectionFreq: "24",
    serviceProvider: "Toyota Ireland",
  },
  {
    id: "38",
    assetNo: "L112",
    mfgYr: "2021",
    make: "Genie",
    model: "GS2046",
    sn: "GEN2046EIL1520",
    description: "M.E.W.P.",
    location: "PM2",
    inspectionFreq: "12",
    serviceProvider: "Reddilift",
  },
  {
    id: "39",
    assetNo: "L113",
    mfgYr: "2019",
    make: "ORONA",
    model: "MRL",
    sn: "EXIE75702MW",
    description: "Electric Hydraulic Passenger Lift",
    location: "PM1",
    inspectionFreq: "12",
    serviceProvider: "Orona Mid Western",
  },
  {
    id: "40",
    assetNo: "L114",
    mfgYr: "2019",
    make: "Hyster",
    model: "H3.0FT",
    sn: "F147V02741T",
    description: "LPG Forklift",
    location: "PM4",
    inspectionFreq: "24",
    serviceProvider: "Hyster Ltd.",
  },
  {
    id: "41",
    assetNo: "L115",
    mfgYr: "2020",
    make: "Combilift",
    model: "C3000",
    sn: "C00031025",
    description: "Combi Lift",
    location: "PM3",
    inspectionFreq: "12",
    serviceProvider: "Combilift Ltd.",
  },
  {
    id: "42",
    assetNo: "L116",
    mfgYr: "2021",
    make: "Toyota",
    model: "8FBM20T",
    sn: "35016785",
    description: "Battery Forklift",
    location: "PM2",
    inspectionFreq: "24",
    serviceProvider: "Toyota Ireland",
  },
  {
    id: "43",
    assetNo: "L117",
    mfgYr: "2022",
    make: "Genie",
    model: "GS3246",
    sn: "GEN3246EIL1925",
    description: "M.E.W.P.",
    location: "PM4",
    inspectionFreq: "12",
    serviceProvider: "Reddilift",
  },
  {
    id: "44",
    assetNo: "L118",
    mfgYr: "2023",
    make: "Combilift",
    model: "C3000",
    sn: "C00033340",
    description: "Combi Lift",
    location: "PM1",
    inspectionFreq: "12",
    serviceProvider: "Combilift Ltd.",
  },
  {
    id: "45",
    assetNo: "L119",
    mfgYr: "2021",
    make: "Toyota",
    model: "8FBM20T",
    sn: "35023789",
    description: "Battery Forklift",
    location: "PM3",
    inspectionFreq: "12",
    serviceProvider: "Toyota Ireland",
  },
  {
    id: "46",
    assetNo: "L120",
    mfgYr: "2018",
    make: "Genie",
    model: "GS2632",
    sn: "GEN2632XIL1625",
    description: "M.E.W.P.",
    location: "PM2",
    inspectionFreq: "12",
    serviceProvider: "Reddilift",
  },
  {
    id: "47",
    assetNo: "L121",
    mfgYr: "2019",
    make: "Toyota",
    model: "8FBM20T",
    sn: "35025780",
    description: "Battery Forklift",
    location: "PM4",
    inspectionFreq: "12",
    serviceProvider: "Toyota Ireland",
  },
]
